# Generated by Django 4.0.2 on 2022-05-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
