# Generated by Django 4.0.2 on 2022-05-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='name',
        ),
    ]
