# Generated by Django 4.0.2 on 2022-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amout',
            field=models.IntegerField(default=0),
        ),
    ]
