# Generated by Django 4.0.2 on 2022-05-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_amout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amout',
            new_name='amount',
        ),
    ]
